# Generated by Django 4.2.5 on 2023-10-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0002_anuncio_campo_tipousuario_user_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anuncio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clasesYa.anuncio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clasesYa.tipousuario'),
        ),
    ]
