# Generated by Django 4.2.4 on 2023-10-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0004_alter_user_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipoUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clasesYa.tipousuario'),
        ),
    ]
