# Generated by Django 4.2.5 on 2023-11-21 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0006_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='fecha_reserva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='usuario_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_reservadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_profesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
