# Generated by Django 4.2.5 on 2023-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0006_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(),
        ),
    ]
