# Generated by Django 4.2.5 on 2023-11-21 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0007_alter_reserva_fecha_alter_reserva_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnoChat', to=settings.AUTH_USER_MODEL)),
                ('idProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesorChat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('idChatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasesYa.chatroom')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
