# Generated by Django 4.2.5 on 2023-11-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0007_clase_fecha_reserva_clase_usuario_reserva_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clase',
        ),
    ]
