# Generated by Django 4.2.5 on 2023-11-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0009_tabladeprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tablaDePrueba',
        ),
    ]
