# Generated by Django 4.2.5 on 2023-11-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0010_reserva_delete_reservaclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechaHora',
            field=models.DateTimeField(),
        ),
    ]
