# Generated by Django 4.2.5 on 2023-11-29 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0010_delete_tabladeprueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
