# Generated by Django 4.2.5 on 2023-11-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasesYa', '0011_reserva_estado_alter_reserva_fechahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaHora',
            field=models.DateTimeField(blank=True),
        ),
    ]
